In [18]:
import pandas as pd

# Importer le fichier vgsales.csv
df = pd.read_csv('./data/vgsales.csv')

df.query("Platform == 'NES'")

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
1,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
9,10,Duck Hunt,NES,1984.0,Shooter,Nintendo,26.93,0.63,0.28,0.47,28.31
22,23,Super Mario Bros. 3,NES,1988.0,Platform,Nintendo,9.54,3.44,3.84,0.46,17.28
96,97,Super Mario Bros. 2,NES,1988.0,Platform,Nintendo,5.39,1.18,0.70,0.19,7.46
127,128,The Legend of Zelda,NES,1986.0,Action,Nintendo,3.74,0.93,1.69,0.14,6.51
...,...,...,...,...,...,...,...,...,...,...,...
5862,5864,Famista '91,NES,1990.0,Sports,Namco Bandai Games,0.00,0.00,0.30,0.00,0.30
6161,6163,Famista '92,NES,1991.0,Sports,Namco Bandai Games,0.00,0.00,0.28,0.00,0.28
10309,10311,Final Fantasy I & II,NES,1994.0,Role-Playing,Square,0.00,0.00,0.11,0.00,0.11
11985,11987,Teenage Mutant Ninja Turtles: Tournament Fighters,NES,1992.0,Fighting,Konami Digital Entertainment,0.04,0.01,0.02,0.00,0.07
12636,12638,Adventures of Lolo,NES,1989.0,Puzzle,HAL Laboratory,0.06,0.00,0.00,0.00,0.06

In [10]:
sum(df.JP_Sales)
# df.JP_Sales.sum()

1291.02

In [12]:
len(df.query("Year >= 2008"))

8004

In [17]:
f'{round((len(df.query("Platform == 'Wii'")) / len(df)) * 100, 2)}%'

'7.98%'